name: tnbc_resistomics
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.3
  - bioconductor-tcgabiolinks
  - bioconductor-deseq2
  - bioconductor-enhancedvolcano
  - r-tidyverse
